### PR TITLE
Buildtools

### PR DESCRIPTION
**Pull request by jefffohl**
@rhyolight - I moved things around a lot. Things I did:

* Added `package.json` to install npm packages, used for dev tools.
* Using `gulp` for the build of the javascript app, and running tests on the javascript. Note that this is separate from any of the server stuff - this is all for client-side javascript
* Created `charts` directory, where the client-side stuff resides (may change the name of this in the future).
* Added `bower.json` file for managing bower packages, which are now located in the `charts` directory.
* Added `.editorconfig` file to ensure that everyone is using the same whitespace rules, etc.
* Added testing framework, which consists of PhantomJS, Jasmine and Karma.

Running `gulp` from the root directory will:

* Run tests (right now that is skipped, because there are none).
* Clean out the `static` directory
* Concatenate all of the external libraries into a single file called, `external.js` and put it into the `static` directory.
* Concatenate and minify the application JS into a single file called `app.js` and put it into the `static` directory.
* Compile the LESS stylesheets (including bootstrap and the local LESS files), and write that to `stylesheet.css` in the `static` directory.
* Move files, like fonts into the `static` directory.

There is more we can do, such as auto-detect when changes are made, and automatically run gulp commands, but this is a good start.

### CODE REVIEW

**Comment by jefffohl** [comment]
I noticed that you have updated moment, and made some other small changes recently, which conflict with this PR. Let me know when you have a chance to review and we can chat.

**Comment by rhyolight** [comment]
:+1:

**Comment by rhyolight** [comment]
Do you need help with the merge?

**Comment by jefffohl** [comment]
No, I just wanted to make sure you were OK with such big changes. I may make a new PR that is merge-able.

**Comment by jefffohl** [comment]
Closing this to replace it with another.

**Pull request closed without merging**
